name: QUANT_TRADE

on:
  schedule:
    - cron: '0 7,12,16,20 * * *'
    
  workflow_dispatch:

jobs:
  run-trading:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Create .env
        run: |
          echo "SENDER_EMAIL=${{secrets.SENDER_EMAIL}}" >> .env
          echo "EMAIL_APP_PASSWORD=${{secrets.EMAIL_APP_PASSWORD}}" >> .env
          echo "RECEIVER_EMAILS=${{secrets.RECEIVER_EMAILS}}">> .env
          echo "NEWS_API_KEY=${{secrets.NEWS_API_KEY}}" >> .env
          
        
      - name: Run quant_trade
        run: |
          python trading_agent.py
